function buildProxyWorker_(route) {
  const config = JSON.stringify({
    hostname: route.hostname,
    pathPrefix: route.pathPrefix,
    targetUrl: route.targetUrl,
    stripPrefix: route.stripPrefix,
    deliveryMode: route.deliveryMode === 'full_proxy' ? 'full_proxy' : 'redirect',
  });

  return [
    "const ROUTE = " + config + ";",
    "addEventListener('fetch', event => event.respondWith(handleRequest(event.request)));",
    "async function handleRequest(request) {",
    "  const incoming = new URL(request.url);",
    "  const base = new URL(ROUTE.targetUrl);",
    "  if (ROUTE.deliveryMode === 'full_proxy' && incoming.searchParams.get('__gas_rpc') === '1') {",
    "    return proxyGasRpc(request, base);",
    "  }",

    "  const corsTarget = incoming.searchParams.get('__gas_cors_proxy');",
    "  if (ROUTE.deliveryMode === 'full_proxy' && corsTarget) {",
    "    return proxyGoogleRuntime(request, corsTarget);",
    "  }",
    "  let suffix = incoming.pathname;",
    "  if (ROUTE.stripPrefix && ROUTE.pathPrefix !== '/' && suffix.startsWith(ROUTE.pathPrefix)) {",
    "    suffix = suffix.slice(ROUTE.pathPrefix.length);",
    "  }",
    "  if (suffix && suffix !== '/') base.pathname = joinPath(base.pathname, suffix);",
    "  base.search = incoming.search;",
    "  if (ROUTE.deliveryMode === 'full_proxy' && request.method === 'GET' && isGoogleAppsScript(base)) {",
    "    return serveGasAppShell(base, incoming.pathname);",
    "  }",
    "  if (ROUTE.deliveryMode === 'redirect' && request.method === 'GET' && isGoogleAppsScript(base)) {",
    "    return new Response(null, { status: 302, headers: { location: base.toString(), 'x-gas-route-mode': 'redirect', 'cache-control': 'no-store' } });",
    "  }",
    "  const headers = new Headers(request.headers);",
    "  headers.delete('host');",
    "  headers.set('x-forwarded-host', incoming.hostname);",
    "  headers.set('x-forwarded-proto', 'https');",
    "  const init = { method: request.method, headers, redirect: 'follow' };",
    "  if (!['GET', 'HEAD'].includes(request.method)) init.body = request.body;",
    "  const response = await fetch(base.toString(), init);",
    "  const responseHeaders = new Headers(response.headers);",
    "  responseHeaders.set('x-gas-route-mode', ROUTE.deliveryMode);",
    "  const contentType = responseHeaders.get('content-type') || '';",
    "  if (contentType.includes('text/html')) {",
    "    let html = await response.text();",

    "    const baseTag = '<base href=\"' + base.origin + '/\">';",
    "    html = /<head[^>]*>/i.test(html) ? html.replace(/<head([^>]*)>/i, '<head$1>' + baseTag) : baseTag + html;",
    "    if (ROUTE.deliveryMode === 'full_proxy') html = injectCorsBridge(html, incoming.pathname, base.toString());",
    "    const csp = responseHeaders.get('content-security-policy');",
    "    if (csp) responseHeaders.set('content-security-policy', allowBaseOrigin(csp, base.origin));",
    "    if (ROUTE.deliveryMode === 'full_proxy') responseHeaders.set('refresh', '3; url=' + base.toString());",
    "    responseHeaders.delete('content-length');",
    "    responseHeaders.delete('content-encoding');",
    "    return new Response(html, { status: response.status, headers: responseHeaders });",
    "  }",
    "  return new Response(response.body, { status: response.status, headers: responseHeaders });",
    "}",
    "function joinPath(left, right) {",
    "  return (left.replace(/\\/$/, '') + '/' + right.replace(/^\\//, '')).replace(/\\/{2,}/g, '/');",
    "}",
    "function allowBaseOrigin(csp, origin) {",
    "  if (/base-uri\\s+[^;]*/i.test(csp)) {",
    "    return csp.replace(/base-uri\\s+[^;]*/i, function (directive) {",
    "      return directive.includes(origin) ? directive : directive + ' ' + origin;",
    "    });",
    "  }",
    "  return csp.replace(/;?\\s*$/, ';base-uri ' + origin);",
    "}",
    "function isGoogleAppsScript(url) {",
    "  return url.hostname === 'script.google.com' && /^\\/macros\\/s\\/[^/]+\\/exec(?:\\/|$)/.test(url.pathname);",
    "}",
    "async function serveGasAppShell(base, endpointPath) {",
    "  const sourceUrl = new URL(base.toString());",
    "  sourceUrl.searchParams.set('__full_proxy_html', '1');",
    "  const response = await fetch(sourceUrl.toString(), { redirect: 'follow' });",
    "  if (!response.ok) return new Response('Unable to load GAS app source', { status: 502 });",
    "  let payload;",
    "  try { payload = await response.json(); } catch (_) { return new Response('Invalid GAS app source response', { status: 502 }); }",
    "  if (!payload || !payload.ok || typeof payload.html !== 'string') return new Response('GAS app source is unavailable', { status: 502 });",
    "  const shim = buildGasRunShim(endpointPath);",
    "  const html = /<head[^>]*>/i.test(payload.html) ? payload.html.replace(/<head([^>]*)>/i, '<head$1>' + shim) : shim + payload.html;",
    "  return new Response(html, { status: 200, headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store', 'x-gas-route-mode': 'full_proxy', 'x-gas-runtime': 'worker-native-rpc' } });",
    "}",
    "function buildGasRunShim(endpointPath) {",
    "  const endpoint = JSON.stringify(endpointPath + '?__gas_rpc=1');",
    "  const code = '(function(){const endpoint=' + endpoint + ';function runner(success,failure){return new Proxy({}, {get:function(_,name){if(name===\"withSuccessHandler\")return function(fn){return runner(fn,failure)};if(name===\"withFailureHandler\")return function(fn){return runner(success,fn)};return function(){const args=Array.prototype.slice.call(arguments);fetch(endpoint,{method:\"POST\",headers:{\"content-type\":\"application/json\"},body:JSON.stringify({functionName:String(name),args:args})}).then(function(response){return response.json()}).then(function(payload){if(!payload.ok)throw new Error(payload.error||\"RPC failed\");if(success)success(payload.result)}).catch(function(error){if(failure)failure(error);else console.error(error)})}}})}window.google=window.google||{};window.google.script=window.google.script||{};window.google.script.run=runner();window.google.script.host=window.google.script.host||{close:function(){window.close()}}})();';",
    "  return '<script>' + code + '<\\/script>';",
    "}",
    "async function proxyGasRpc(request, target) {",
    "  if (request.method === 'OPTIONS') return corsPreflight(request);",
    "  if (request.method !== 'POST') return new Response('Method not allowed', { status: 405, headers: { allow: 'POST, OPTIONS' } });",
    "  const body = await request.arrayBuffer();",
    "  const init = { method: 'POST', headers: { 'content-type': 'application/json' }, body: body, redirect: 'manual' };",
    "  let response = await fetch(target.toString(), init);",
    "  if (response.status >= 300 && response.status < 400) {",
    "    const location = response.headers.get('location');",
    "    if (!location || !isAllowedGasRedirect(location)) return new Response('Invalid GAS RPC redirect', { status: 502 });",
    "    response = await fetch(location, { method: 'GET', redirect: 'follow' });",
    "  }",
    "  const headers = new Headers(response.headers);",
    "  headers.delete('content-length');",
    "  headers.delete('content-encoding');",
    "  headers.set('content-type', 'application/json; charset=utf-8');",
    "  headers.set('cache-control', 'no-store');",
    "  headers.set('access-control-allow-origin', '*');",
    "  return new Response(response.body, { status: response.status, headers: headers });",
    "}",

    "function injectCorsBridge(html, endpointPath, fallbackUrl) {",
    "  const nonce = (html.match(/<script[^>]+nonce=[\"']([^\"']+)[\"']/i) || [])[1] || '';",
    "  const nonceAttr = nonce ? ' nonce=\"' + nonce + '\"' : '';",
    "  const endpoint = JSON.stringify(endpointPath + '?__gas_cors_proxy=');",
    "  const fallback = JSON.stringify(fallbackUrl);",
    "  const safeFallback = fallbackUrl.replace(/&/g, '&amp;').replace(/\"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');",
    "  const code = '(function(){const endpoint=location.origin+' + endpoint + ';const fallback=' + fallback + ';const timer=setTimeout(function(){location.replace(fallback)},3000);window.addEventListener(\"beforeunload\",function(){clearTimeout(timer)});const rewrite=function(value){try{const url=new URL(typeof value===\"string\"?value:value.url,location.href);if(url.hostname===\"script.google.com\"||url.hostname.endsWith(\"-script.googleusercontent.com\")){return endpoint+encodeURIComponent(url.href)}}catch(e){}return value};const nativeFetch=window.fetch;window.fetch=function(input,init){return nativeFetch.call(this,rewrite(input),init)};const nativeOpen=XMLHttpRequest.prototype.open;XMLHttpRequest.prototype.open=function(method,url){arguments[1]=rewrite(url);return nativeOpen.apply(this,arguments)}})();';",
    "  const bridge = '<meta http-equiv=\"refresh\" content=\"3;url=' + safeFallback + '\"><script' + nonceAttr + '>' + code + '<\\/script>';",
    "  return /<head[^>]*>/i.test(html) ? html.replace(/<head([^>]*)>/i, '<head$1>' + bridge) : bridge + html;",
    "}",
    "async function proxyGoogleRuntime(request, rawTarget) {",
    "  if (request.method === 'OPTIONS') return corsPreflight(request);",
    "  let target;",
    "  try { target = new URL(rawTarget); } catch (_) { return new Response('Invalid proxy target', { status: 400 }); }",
    "  if (!isAllowedGoogleRuntime(target)) return new Response('Proxy target is not allowed', { status: 403 });",
    "  const headers = new Headers(request.headers);",
    "  ['host', 'origin', 'referer', 'cookie', 'cf-connecting-ip', 'cf-ipcountry', 'cf-ray', 'x-forwarded-host', 'x-forwarded-proto'].forEach(function (name) { headers.delete(name); });",
    "  const init = { method: request.method, headers: headers, redirect: 'follow' };",
    "  if (!['GET', 'HEAD'].includes(request.method) && request.body) init.body = request.body;",
    "  const response = await fetch(target.toString(), init);",
    "  const responseHeaders = new Headers(response.headers);",
    "  ['content-length', 'content-encoding', 'set-cookie', 'content-security-policy', 'x-frame-options'].forEach(function (name) { responseHeaders.delete(name); });",
    "  responseHeaders.set('access-control-allow-origin', '*');",
    "  responseHeaders.set('access-control-expose-headers', '*');",
    "  responseHeaders.set('cache-control', 'no-store');",
    "  return new Response(response.body, { status: response.status, headers: responseHeaders });",
    "}",
    "function corsPreflight(request) {",
    "  const requestedHeaders = request.headers.get('access-control-request-headers') || 'content-type';",
    "  return new Response(null, { status: 204, headers: { 'access-control-allow-origin': '*', 'access-control-allow-methods': 'GET,HEAD,POST,OPTIONS', 'access-control-allow-headers': requestedHeaders, 'access-control-max-age': '86400', 'x-gas-route-mode': 'full_proxy' } });",
    "}",
    "function isAllowedGoogleRuntime(url) {",
    "  return url.protocol === 'https:' && (url.hostname === 'script.google.com' || url.hostname.endsWith('-script.googleusercontent.com'));",
    "}",
    "function isAllowedGasRedirect(rawUrl) {",
    "  try { const url = new URL(rawUrl); return url.protocol === 'https:' && url.hostname === 'script.googleusercontent.com' && url.pathname === '/macros/echo'; } catch (_) { return false; }",
    "}",
  ].join('\n');
}
